### ISSUE TITLE
checkpoint_dir

### ISSUE THREAD

**Issue by grenache** [CompVis/adaptive-style-transfer#10]
While trying to [port to Colab](https://github.com/grenache/style4colab), we ran across this issue in [model.py](https://github.com/CompVis/adaptive-style-transfer/blob/master/model.py)
![screen shot 2018-10-23 at 7 09 15 pm](https://user-images.githubusercontent.com/12416590/47453396-76484180-d781-11e8-9b50-f3a18c23aa29.png)

**Comment by asanakoy** [comment]
Could you please describe the issue in details?

**Comment by grenache** [comment]
The above screenshot is from someone who I asked to debug. 

Not sure if this is helpful, but this is the notebook output:
`Inference.`
`Start inference.`
` [*] Reading latest checkpoint from folder ./models/model_van-gogh/checkpoint.`
 `[*] Reading latest checkpoint from folder ./models/model_van-gogh/checkpoint_long.`
 `[!] Load failed...`
`0it [00:00, ?it/s]`
`Inference is finished.`

**Comment by asanakoy** [comment]
Check that the model snapshot file is in the checkpoint dir. Try to print all the paths. Look like it simply doesn't find the checkpoint file.

**Comment by grenache** [comment]
once the main.py is run the 4 files in the in models/model_van-gogh are moved to ./models/checkpoint_long/
`checkpoint`
`model16_van-gogh_bks10_flw100_300000.ckpt-300000.data-00000-of-00001`
`model16_van-gogh_bks10_flw100_300000.ckpt-300000.index`
`model16_van-gogh_bks10_flw100_300000.ckpt-300000.meta`

Directories are created in ./models/
`checkpoint`
`checkpoint_long`
`inference`
`inference_ckpt0_sz1280`
`sample`

All are empty besides `checkpoint_long` that are apart of the tar.gz.  `checkpoint` remains the same.

**Comment by dimakot55** [comment]
That seems to be correct. I guess that the problem lies in the filesytem naming convention used in Colab: we've only tried to run the script on local machine so I can't share my own experience with you. I would recommend you to manually output the values of os.listdir(checkpoint_dir) and os.path.join(checkpoint_dir, ckpt_name) and dig in this direction for a solution. You can also check your current working directory in Colab using something like os.getcwd().

**Comment by asanakoy** [comment]
Closed due to inactivity. Feel free to open it again if you have any further questions.
